### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by KyGost** [RangerMauve/hyperdrive-publisher#1]
To get this to work with Github Actions:
1. Enter `Actions` on top, in the chosen repo
2. Click `set up a workflow yourself` up top
3. Put the below into the file:
```yml
name: Publish
on:
  release:
    types: [published]
```

**Comment by KyGost** [comment]
@RangerMauve trying to figure out how one might do this; its very new to me haha
Any ideas?

**Comment by RangerMauve** [comment]
I think you just need a job that looks something like

```yaml
name: Publish to hyperdrive

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
       - name: Check out Git repository
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Publish to hyperdrive
        run: npx hyperdrive-publisher sync ${{ secrets.SEED }}
```
